### ISSUE TITLE
load trained model 

### ISSUE THREAD

**Issue by rginjapan** [y0ast/DUE#10]
Could you add a example about how to load trained modle and likelyhood model for prediction in toymodel_regression script?

**Comment by rginjapan** [comment]
I have tried with:
torch.save(model.state_dict(), "model.pt")


```
if likelihood is not None:
    torch.save(likelihood.state_dict(), "likelihood.pt")

model.load_state_dict(torch.load("/home/sly/DeepLIO-master/model.pt"))
model.eval()
if DUE:
    likelihood.load_state_dict(torch.load("/home/sly/DeepLIO-master/likelihood.pt"))
    likelihood.eval()

```
If I am wrong, plz let me know.

**Comment by y0ast** [comment]
The pre-trained model is only available for the CIFAR-10 code.

Pytorch has great documentation loading/saving.
