### ISSUE TITLE
initial values selection

### ISSUE THREAD

**Issue by rginjapan** [y0ast/DUE#11]
About `def initial_values(train_dataset, feature_extractor, n_inducing_points)`:
In toymodel regression script, the train_dataset is the whole training datset, could it be the mini-batch instead of whole training dataset?

**Comment by rginjapan** [comment]
In the paper, you mentioned the in Algotithm 1, the initial inducing points and initial length scale are calculated from a random subset of p points of our training data.

However, this [cat](https://github.com/y0ast/DUE/blob/main/due/dkl.py#:~:text=f_X_samples%20%3D%20torch.cat(f_X_samples)) is cat all the features caluctead from feature extractor on the whole dataset.

so these two initial params. are based on whole dataset or a random subset of training dataset??

**Comment by y0ast** [comment]
They are usually based on a subset, but if the dataset is small I just use all of it.
