### ISSUE TITLE
__

### ISSUE THREAD

**Issue by swyoon** [y0ast/DUE#13]
I have deleted the issue. sorry for bothering you.

**Comment by rginjapan** [comment]
> I have deleted the issue. sorry for bothering you.

Could u plz tell me why you closed, I have the same consideration as you mentioned before, thanks!

**Comment by y0ast** [comment]
Not a bother!

I think the original question was about preprocessing. The relevant line for that is here: https://github.com/y0ast/DUE/blob/main/lib/evaluate_ood.py#L13

So the "out of distribution" dataset is indeed preprocessed like the "in distribution" set.
